### ISSUE TITLE
[Request] Adding a transpile step for Qiskit circuits

### ISSUE THREAD

**Issue by stephendiadamo** [qcware/qusetta#6]
Since this library doesn't convert all gates from Qiskit to Quasar, it could be useful to add a (potentially optional) transpile step to ensure the circuit is composed of supported gates. To get this working, I had to check the code to find which gates are supported and then add the transpile step myself. Would be nice if this was a feature.

**Comment by vputz** [comment]
Stephen:

I don't know if Joe is actively maintaining qusetta; we at qcware in general aren't, but I did start a second translation project we also host which is... well, more complex and bloated but also more comprehensively tested and in active development (https://github.com/qcware/qcware_transpile, not released to pypi yet and the name is pretty boring).  I could use your same help testing that one if you want to take a look (sorry, documentation is in pretty early stages).  I'm taking both this and your other issue there.  Although I don't do the transpile step yet, that would be relatively easy because you can programmatically query the translation table a little more easily; have not tested the "multiple qubit register" problem yet (qiskit and quasar have some different assumptions; I'm still working out how to handle "measure gates" in qiskit when quasar doesn't really support them but rather measures or returns the whole statevector).

(although of course feel free to keep using qusetta!  I'm just not sure how active it will be)

**Comment by stephendiadamo** [comment]
Thanks for the information! No problem, it was my first time trying out the Forge platform and the two issues I reported would have saved me an hour to two, but not a big hassle. I'll check out the repo you've linked in my future experiments. Thanks again.

**Comment by jtiosue** [comment]
Thanks for raising this @stephendiadamo. If I get the chance, I may try to add support for more qiskit gates in qusetta. But I agree with @vputz that `qcware_transpile` is a better repository to look into.
